/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.digital_wallet.avroschema.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TransactionAvcEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -1913070475179830489L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TransactionAvcEvent\",\"namespace\":\"com.digital_wallet.avroschema.avro\",\"fields\":[{\"name\":\"transactionType\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"transactionStatus\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"walletId\",\"type\":\"long\"},{\"name\":\"userId\",\"type\":\"long\"},{\"name\":\"amount\",\"type\":{\"type\":\"bytes\",\"logicalType\":\"decimal\",\"precision\":19,\"scale\":4}},{\"name\":\"transactionId\",\"type\":\"long\"},{\"name\":\"timestamp\",\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();
  static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.Conversions.DecimalConversion());
  }

  private static final BinaryMessageEncoder<TransactionAvcEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TransactionAvcEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TransactionAvcEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TransactionAvcEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TransactionAvcEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TransactionAvcEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TransactionAvcEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TransactionAvcEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TransactionAvcEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String transactionType;
  private java.lang.String transactionStatus;
  private long walletId;
  private long userId;
  private java.math.BigDecimal amount;
  private long transactionId;
  private long timestamp;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TransactionAvcEvent() {}

  /**
   * All-args constructor.
   * @param transactionType The new value for transactionType
   * @param transactionStatus The new value for transactionStatus
   * @param walletId The new value for walletId
   * @param userId The new value for userId
   * @param amount The new value for amount
   * @param transactionId The new value for transactionId
   * @param timestamp The new value for timestamp
   */
  public TransactionAvcEvent(java.lang.String transactionType, java.lang.String transactionStatus, java.lang.Long walletId, java.lang.Long userId, java.math.BigDecimal amount, java.lang.Long transactionId, java.lang.Long timestamp) {
    this.transactionType = transactionType;
    this.transactionStatus = transactionStatus;
    this.walletId = walletId;
    this.userId = userId;
    this.amount = amount;
    this.transactionId = transactionId;
    this.timestamp = timestamp;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return transactionType;
    case 1: return transactionStatus;
    case 2: return walletId;
    case 3: return userId;
    case 4: return amount;
    case 5: return transactionId;
    case 6: return timestamp;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  private static final org.apache.avro.Conversion<?>[] conversions =
      new org.apache.avro.Conversion<?>[] {
      null,
      null,
      null,
      null,
      new org.apache.avro.Conversions.DecimalConversion(),
      null,
      null,
      null
  };

  @Override
  public org.apache.avro.Conversion<?> getConversion(int field) {
    return conversions[field];
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: transactionType = value$ != null ? value$.toString() : null; break;
    case 1: transactionStatus = value$ != null ? value$.toString() : null; break;
    case 2: walletId = (java.lang.Long)value$; break;
    case 3: userId = (java.lang.Long)value$; break;
    case 4: amount = (java.math.BigDecimal)value$; break;
    case 5: transactionId = (java.lang.Long)value$; break;
    case 6: timestamp = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'transactionType' field.
   * @return The value of the 'transactionType' field.
   */
  public java.lang.String getTransactionType() {
    return transactionType;
  }


  /**
   * Sets the value of the 'transactionType' field.
   * @param value the value to set.
   */
  public void setTransactionType(java.lang.String value) {
    this.transactionType = value;
  }

  /**
   * Gets the value of the 'transactionStatus' field.
   * @return The value of the 'transactionStatus' field.
   */
  public java.lang.String getTransactionStatus() {
    return transactionStatus;
  }


  /**
   * Sets the value of the 'transactionStatus' field.
   * @param value the value to set.
   */
  public void setTransactionStatus(java.lang.String value) {
    this.transactionStatus = value;
  }

  /**
   * Gets the value of the 'walletId' field.
   * @return The value of the 'walletId' field.
   */
  public long getWalletId() {
    return walletId;
  }


  /**
   * Sets the value of the 'walletId' field.
   * @param value the value to set.
   */
  public void setWalletId(long value) {
    this.walletId = value;
  }

  /**
   * Gets the value of the 'userId' field.
   * @return The value of the 'userId' field.
   */
  public long getUserId() {
    return userId;
  }


  /**
   * Sets the value of the 'userId' field.
   * @param value the value to set.
   */
  public void setUserId(long value) {
    this.userId = value;
  }

  /**
   * Gets the value of the 'amount' field.
   * @return The value of the 'amount' field.
   */
  public java.math.BigDecimal getAmount() {
    return amount;
  }


  /**
   * Sets the value of the 'amount' field.
   * @param value the value to set.
   */
  public void setAmount(java.math.BigDecimal value) {
    this.amount = value;
  }

  /**
   * Gets the value of the 'transactionId' field.
   * @return The value of the 'transactionId' field.
   */
  public long getTransactionId() {
    return transactionId;
  }


  /**
   * Sets the value of the 'transactionId' field.
   * @param value the value to set.
   */
  public void setTransactionId(long value) {
    this.transactionId = value;
  }

  /**
   * Gets the value of the 'timestamp' field.
   * @return The value of the 'timestamp' field.
   */
  public long getTimestamp() {
    return timestamp;
  }


  /**
   * Sets the value of the 'timestamp' field.
   * @param value the value to set.
   */
  public void setTimestamp(long value) {
    this.timestamp = value;
  }

  /**
   * Creates a new TransactionAvcEvent RecordBuilder.
   * @return A new TransactionAvcEvent RecordBuilder
   */
  public static com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder newBuilder() {
    return new com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder();
  }

  /**
   * Creates a new TransactionAvcEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TransactionAvcEvent RecordBuilder
   */
  public static com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder newBuilder(com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder other) {
    if (other == null) {
      return new com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder();
    } else {
      return new com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder(other);
    }
  }

  /**
   * Creates a new TransactionAvcEvent RecordBuilder by copying an existing TransactionAvcEvent instance.
   * @param other The existing instance to copy.
   * @return A new TransactionAvcEvent RecordBuilder
   */
  public static com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder newBuilder(com.digital_wallet.avroschema.avro.TransactionAvcEvent other) {
    if (other == null) {
      return new com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder();
    } else {
      return new com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for TransactionAvcEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TransactionAvcEvent>
    implements org.apache.avro.data.RecordBuilder<TransactionAvcEvent> {

    private java.lang.String transactionType;
    private java.lang.String transactionStatus;
    private long walletId;
    private long userId;
    private java.math.BigDecimal amount;
    private long transactionId;
    private long timestamp;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[0].schema(), other.transactionType);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.transactionStatus)) {
        this.transactionStatus = data().deepCopy(fields()[1].schema(), other.transactionStatus);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.walletId)) {
        this.walletId = data().deepCopy(fields()[2].schema(), other.walletId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[5].schema(), other.transactionId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
    }

    /**
     * Creates a Builder by copying an existing TransactionAvcEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.digital_wallet.avroschema.avro.TransactionAvcEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.transactionType)) {
        this.transactionType = data().deepCopy(fields()[0].schema(), other.transactionType);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.transactionStatus)) {
        this.transactionStatus = data().deepCopy(fields()[1].schema(), other.transactionStatus);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.walletId)) {
        this.walletId = data().deepCopy(fields()[2].schema(), other.walletId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.userId)) {
        this.userId = data().deepCopy(fields()[3].schema(), other.userId);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.amount)) {
        this.amount = data().deepCopy(fields()[4].schema(), other.amount);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.transactionId)) {
        this.transactionId = data().deepCopy(fields()[5].schema(), other.transactionId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.timestamp)) {
        this.timestamp = data().deepCopy(fields()[6].schema(), other.timestamp);
        fieldSetFlags()[6] = true;
      }
    }

    /**
      * Gets the value of the 'transactionType' field.
      * @return The value.
      */
    public java.lang.String getTransactionType() {
      return transactionType;
    }


    /**
      * Sets the value of the 'transactionType' field.
      * @param value The value of 'transactionType'.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder setTransactionType(java.lang.String value) {
      validate(fields()[0], value);
      this.transactionType = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionType' field has been set.
      * @return True if the 'transactionType' field has been set, false otherwise.
      */
    public boolean hasTransactionType() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'transactionType' field.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder clearTransactionType() {
      transactionType = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionStatus' field.
      * @return The value.
      */
    public java.lang.String getTransactionStatus() {
      return transactionStatus;
    }


    /**
      * Sets the value of the 'transactionStatus' field.
      * @param value The value of 'transactionStatus'.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder setTransactionStatus(java.lang.String value) {
      validate(fields()[1], value);
      this.transactionStatus = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionStatus' field has been set.
      * @return True if the 'transactionStatus' field has been set, false otherwise.
      */
    public boolean hasTransactionStatus() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'transactionStatus' field.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder clearTransactionStatus() {
      transactionStatus = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'walletId' field.
      * @return The value.
      */
    public long getWalletId() {
      return walletId;
    }


    /**
      * Sets the value of the 'walletId' field.
      * @param value The value of 'walletId'.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder setWalletId(long value) {
      validate(fields()[2], value);
      this.walletId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'walletId' field has been set.
      * @return True if the 'walletId' field has been set, false otherwise.
      */
    public boolean hasWalletId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'walletId' field.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder clearWalletId() {
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'userId' field.
      * @return The value.
      */
    public long getUserId() {
      return userId;
    }


    /**
      * Sets the value of the 'userId' field.
      * @param value The value of 'userId'.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder setUserId(long value) {
      validate(fields()[3], value);
      this.userId = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'userId' field has been set.
      * @return True if the 'userId' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'userId' field.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder clearUserId() {
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'amount' field.
      * @return The value.
      */
    public java.math.BigDecimal getAmount() {
      return amount;
    }


    /**
      * Sets the value of the 'amount' field.
      * @param value The value of 'amount'.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder setAmount(java.math.BigDecimal value) {
      validate(fields()[4], value);
      this.amount = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'amount' field has been set.
      * @return True if the 'amount' field has been set, false otherwise.
      */
    public boolean hasAmount() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'amount' field.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder clearAmount() {
      amount = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'transactionId' field.
      * @return The value.
      */
    public long getTransactionId() {
      return transactionId;
    }


    /**
      * Sets the value of the 'transactionId' field.
      * @param value The value of 'transactionId'.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder setTransactionId(long value) {
      validate(fields()[5], value);
      this.transactionId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'transactionId' field has been set.
      * @return True if the 'transactionId' field has been set, false otherwise.
      */
    public boolean hasTransactionId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'transactionId' field.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder clearTransactionId() {
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'timestamp' field.
      * @return The value.
      */
    public long getTimestamp() {
      return timestamp;
    }


    /**
      * Sets the value of the 'timestamp' field.
      * @param value The value of 'timestamp'.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder setTimestamp(long value) {
      validate(fields()[6], value);
      this.timestamp = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'timestamp' field has been set.
      * @return True if the 'timestamp' field has been set, false otherwise.
      */
    public boolean hasTimestamp() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'timestamp' field.
      * @return This builder.
      */
    public com.digital_wallet.avroschema.avro.TransactionAvcEvent.Builder clearTimestamp() {
      fieldSetFlags()[6] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TransactionAvcEvent build() {
      try {
        TransactionAvcEvent record = new TransactionAvcEvent();
        record.transactionType = fieldSetFlags()[0] ? this.transactionType : (java.lang.String) defaultValue(fields()[0]);
        record.transactionStatus = fieldSetFlags()[1] ? this.transactionStatus : (java.lang.String) defaultValue(fields()[1]);
        record.walletId = fieldSetFlags()[2] ? this.walletId : (java.lang.Long) defaultValue(fields()[2]);
        record.userId = fieldSetFlags()[3] ? this.userId : (java.lang.Long) defaultValue(fields()[3]);
        record.amount = fieldSetFlags()[4] ? this.amount : (java.math.BigDecimal) defaultValue(fields()[4]);
        record.transactionId = fieldSetFlags()[5] ? this.transactionId : (java.lang.Long) defaultValue(fields()[5]);
        record.timestamp = fieldSetFlags()[6] ? this.timestamp : (java.lang.Long) defaultValue(fields()[6]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TransactionAvcEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<TransactionAvcEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TransactionAvcEvent>
    READER$ = (org.apache.avro.io.DatumReader<TransactionAvcEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










